---
- name: Create Folder
  file:
    path: /opt/repo 
    state: directory
- name: Load Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v1.7.1/prometheus-1.7.1.linux-amd64.tar.gz
    dest: /opt/repo/prometheus-1.7.1.linux-amd64.tar.gz
- name: Load Prometheus Node-Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.14.0/node_exporter-0.14.0.linux-amd64.tar.gz
    dest: /opt/repo/node_exporter-0.14.0.linux-amd64.tar.gz
- name: Load Prometheus Pushgateway
  get_url:
    url: https://github.com/prometheus/pushgateway/releases/download/v0.4.0/pushgateway-0.4.0.linux-amd64.tar.gz
    dest: /opt/repo/pushgateway-0.4.0.linux-amd64.tar.gz
- name: Load Grafana
  get_url:
    url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-4.4.1.linux-x64.tar.gz 
    dest: /opt/repo/grafana-4.4.1.linux-x64.tar.gz
- name: Load Redis
  get_url:
    url: http://download.redis.io/releases/redis-4.0.1.tar.gz
    dest: /opt/repo/redis-4.0.1.tar.gz
- name: Load Cassandra
  get_url:
    url: http://www-eu.apache.org/dist/cassandra/3.11.0/apache-cassandra-3.11.0-bin.tar.gz
    dest: /opt/repo/apache-cassandra-3.11.0-bin.tar.gz
